var ADD_TASK = '/',
UPDATE_TASKS = '/',
DELETE_TASKS = '/delete/tasks/',
ARCHIVED_TASKS = '/archive/',
ARCHIVE_COMPLETED_TASKS = ARCHIVED_TASKS,
API_TASKS = '/api/tasks/',
API_ADD_TASK = API_TASKS,
API_DELETE_TASKS = API_TASKS,
API_ARCHIVE_TASKS = API_TASKS,
API_ARCHIVE = '/api/archive/',
API_TODOS = '/api/todos/';

module.exports = {
  ADD_TASK:ADD_TASK,
  UPDATE_TASKS:UPDATE_TASKS,
  DELETE_TASKS:DELETE_TASKS,
  ARCHIVE_COMPLETED_TASKS:ARCHIVE_COMPLETED_TASKS,
  ARCHIVED_TASKS:ARCHIVED_TASKS,
  API_TASKS:API_TASKS,
  API_ADD_TASK:API_ADD_TASK,
  API_DELETE_TASKS:API_DELETE_TASKS,
  API_ARCHIVE_TASKS:API_ARCHIVE_TASKS,
  API_ARCHIVE:API_ARCHIVE,
  API_TODOS:API_TODOS
};
