var ADD_TASK = '/',
UPDATE_TASKS = '/',
DELETE_COMPLETED_TASKS = '/delete/completed/tasks/';

module.exports = {
  ADD_TASK:ADD_TASK,
  UPDATE_TASKS:UPDATE_TASKS,
  DELETE_COMPLETED_TASKS:DELETE_COMPLETED_TASKS
};
